/*

 TRACKMB.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 19
   Tile set      : C:\Users\7319a\Documents\Programming\Gameboy\Projects\dFTR\Assets\Art\GameBoy Tile Designer\GBR Files\Track.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define trackMapWidth 20
#define trackMapHeight 19
#define trackMapBank 0

extern unsigned char trackMap[];

/* End of TRACKMB.H */
